"use client";

import { formatDateTime } from "@/lib/helpers";
import { Event } from "@/lib/types";
import Link from "next/link";

interface EventDetailPanelProps {
  event: Event;
  onClose: () => void;
}

const formatCoordinate = (value: number) => value.toFixed(5);

const resolveCreatedAt = (value: Event["createdAt"]): Date => {
  if (value instanceof Date) {
    return value;
  }
  if (value && typeof value === "object" && "toDate" in value && typeof (value as { toDate?: () => Date }).toDate === "function") {
    const converted = (value as { toDate: () => Date }).toDate();
    if (converted instanceof Date && !Number.isNaN(converted.valueOf())) {
      return converted;
    }
  }
  if (typeof value === "string" || typeof value === "number") {
    const parsed = new Date(value);
    if (!Number.isNaN(parsed.valueOf())) {
      return parsed;
    }
  }
  return new Date();
};

export default function EventDetailPanel({ event, onClose }: EventDetailPanelProps) {
  const postedAt = resolveCreatedAt(event.createdAt);
  const tags = Array.isArray(event.tags) ? event.tags : [];
  const hasLocation = Boolean(event.location && typeof event.location.lat === "number" && typeof event.location.lng === "number");

  const mapLink = hasLocation
    ? `https://www.google.com/maps/search/?api=1&query=${event.location!.lat},${event.location!.lng}`
    : undefined;

  return (
    <aside className="flex h-full flex-col bg-white">
      <header className="flex items-start justify-between border-b border-gray-200 px-5 py-4">
        <div>
          <p className="text-xs font-semibold uppercase tracking-wide text-blue-600">Hang Out Details</p>
          <h3 className="text-lg font-semibold text-gray-900">{event.title || "Untitled Hang Out"}</h3>
          <p className="mt-1 text-xs text-gray-500">Posted {formatDateTime(postedAt)}</p>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="rounded-full border border-gray-200 bg-white p-2 text-gray-500 transition hover:bg-gray-100 hover:text-gray-700"
          aria-label="Close details"
        >
          ×
        </button>
      </header>

      <div className="flex-1 overflow-y-auto px-5 py-4">
        <section className="space-y-2">
          <h4 className="text-sm font-semibold text-gray-900">Overview</h4>
          <p className="text-sm text-gray-700 leading-relaxed">
            {event.description?.trim() || "No description provided for this hang out."}
          </p>
        </section>

        {tags.length > 0 && (
          <section className="mt-6 space-y-2">
            <h4 className="text-sm font-semibold text-gray-900">Tags</h4>
            <div className="flex flex-wrap gap-2">
              {tags.map((tag) => (
                <span
                  key={tag}
                  className="inline-flex items-center rounded-full bg-blue-50 px-3 py-1 text-xs font-medium text-blue-700"
                >
                  #{tag}
                </span>
              ))}
            </div>
          </section>
        )}

        <section className="mt-6 space-y-2">
          <h4 className="text-sm font-semibold text-gray-900">Location</h4>
          {hasLocation ? (
            <div className="space-y-2 rounded-xl border border-gray-200 bg-gray-50 p-3 text-xs text-gray-700">
              <p>
                Coordinates: {formatCoordinate(event.location!.lat)}, {formatCoordinate(event.location!.lng)}
              </p>
              {mapLink && (
                <Link
                  href={mapLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 transition hover:text-blue-700"
                >
                  Open in Maps →
                </Link>
              )}
            </div>
          ) : (
            <p className="text-sm text-gray-600">No location data available for this hang out yet.</p>
          )}
        </section>

        <section className="mt-6 space-y-2">
          <h4 className="text-sm font-semibold text-gray-900">Source</h4>
          <p className="text-sm text-gray-700">
            {event.source === "AI"
              ? "Generated by AI concierge"
              : "Created by the community"}
          </p>
        </section>
      </div>
    </aside>
  );
}
